name: fed-pbt
channels:
  - pytorch
  - defaults
dependencies:
  - pip=19.0
  - cython=0.29.0
  - numpy=1.15.1
  - pip:
    - ray[debug]
      #- "--editable=git+https://github.com/ray-project/ray.git#egg=ray&#subdirectory=python"
